name: Junie
run-name: Junie run ${{ inputs.run_id }}

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "id of workflow process"
        required: true
      workflow_params:
        description: "stringified params"
        required: true

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/jos-ej-issue.yml
    with:
      workflow_params: ${{ inputs.workflow_params }}
